import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Adopt Bamboo System',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-between items-center p-4 gap-4 h-16 bg-white shadow-sm">
            {/* Logo */}
            <div className="flex items-center">
              <Link href="/">
                <Image
                  src="/bamboo-logo.svg"
                  alt="Adopt Bamboo Logo"
                  width={120}
                  height={40}
                  priority
                />
              </Link>
            </div>
            
            {/* Navigation */}
            <div className="flex items-center gap-6">
              <Link 
                href="/package" 
                className="text-green-700 hover:text-green-800 font-medium transition-colors"
              >
                Packages
              </Link>
              <SignedIn>
                <Link 
                  href="/dashboard" 
                  className="text-green-700 hover:text-green-800 font-medium transition-colors"
                >
                  Dashboard
                </Link>
              </SignedIn>
            </div>
            
            {/* Authentication Buttons */}
            <div className="flex items-center gap-3">
              <SignedOut>
                <SignInButton>
                  <button className="bg-green-100 hover:bg-green-200 text-green-700 border border-green-300 rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer transition-colors">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-green-600 hover:bg-green-700 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer transition-colors">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
